version: '3.8'
services:
  nginx:
    build: .
    volumes:
     - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"
  datadog: # ref: https://docs.datadoghq.com/integrations/faq/compose-and-the-datadog-agent/
    links:
     - nginx # Connect the Datadog Agent container to the Nginx container
    image: gcr.io/datadoghq/agent:7.27.0 # ref: https://console.cloud.google.com/gcr/images/datadoghq/GLOBAL/agent
    environment:
     - DD_API_KEY=${DD_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - ./datadog/conf.yaml:/etc/datadog-agent/conf.d/nginx.d/conf.yaml
